### PR TITLE
some changes

### PR DESCRIPTION
**Pull request by 6forwater29**

### CODE REVIEW

**Comment by jindongwang** [comment]
Hi, I think you should not pull request here since this is your own information.

**Comment by 6forwater29** [comment]
Sorry,!!!I'm not really good with this！！！
what should I do？
I‘m really sorry!!!


天梯散猫
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jindongwang/jindongwang.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月5日(星期三) 晚上9:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jindongwang/jindongwang.github.io] some changes (PR #2)





 
Hi, I think you should not pull request here since this is your own information.

**Comment by jindongwang** [comment]
You should do nothing to this repo. If you want to use it for your own website, you should fork it to your own github, then modify things in your own repo. After that, just commit and push. You may need to search and learn the basics of git and github.

**Comment by 6forwater29** [comment]
I have forked your repo! And I changed some things and then push them to the my repo!&nbsp;Maybe I shouldn't pull some quest to your repo later!
I'm really sorry for disturbing you for that!!!




天梯散猫
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jindongwang/jindongwang.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月5日(星期三) 晚上9:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jindongwang/jindongwang.github.io] some changes (PR #2)





 
You should do nothing to this repo. If you want to use it for your own website, you should fork it to your own github, then modify things in your own repo. After that, just commit and push. You may need to search and learn the basics of git and github.

**Comment by jindongwang** [comment]
Take it easy.

**Pull request closed without merging**
